### ISSUE TITLE
Figure out are.na "createdAt" data

### ISSUE THREAD

**Issue by Schwartz10** [openworklabs/streams#2]
Are.na data comes back with a couple fields that we could use for time?
`connected_at`
`created_at`
`updated_at`

right now we're using `connected_at`, but is that right?

**Comment by listenaddress** [comment]
`connected_at` is actually what we want. If it's one of our blocks, it will be the same as `created_at` and if we connect someone else's block, `connected_at` will be when we add it to our channel.
